### ISSUE TITLE
using UDMABUF in V4L2_MEMORY_USERPTR cannot be executed on x86

### ISSUE THREAD

**Issue by Homio** [h4tr3d/v4l2-capture-complex#1]
Hi,
      I have download your code, and succeed compile on x86, and changed the function of cma_frame_allocator with below code:
```
    explicit cma_frame_allocator(size_t buffers)
        : dmabuf("udmabuf@0x00")
    {
        assert(buffers <= 4);
        ptr = reinterpret_cast<uint8_t*>(dmabuf.get());
        buf[0] = ptr + 0 * single_buffer_size;
        buf[1] = ptr + 1 * single_buffer_size;
        buf[2] = ptr + 2 * single_buffer_size;
        buf[3] = ptr + 3 * single_buffer_size;
        // Write once to allocate physical memory to u-dma-buf virtual space.
        // Note: Do not use memset() for this.
        //       Because it does not work as expected.
        {
            uint64_t* word_ptr = reinterpret_cast<uint64_t*>(ptr);
            size_t    words    = 4*single_buffer_size/sizeof(uint64_t);
            for(int i = 0 ; i < words; i++) {
                word_ptr[i] = 0;
            }
        }
    }
```
But I cannot succeed executing it, the errno returns EFAULT when do the ioctl: VIDIOC_QBUF.
Can you give me a last code which you succeed executed.
Best wishes!

**Comment by h4tr3d** [comment]
Hi! Obviously, you must bring-up u-dma-buf before using it. Look into: https://github.com/ikwzm/udmabuf.

Also, on x86 you can just allocate memory using new[]/malloc() to use with `V4L2_MEMORY_USERPTR`. Most devices can handle it via setting up DMA scatter/gather mechanism to compose separate physical chunks into one logical buffer.

CMA and UDMABUF mostly a solution for embedded platforms, where there are hardware blocks and DMA implementations that can't work in scatter-gather mode and requires continuous physical memory blocks.

**Comment by Homio** [comment]
Hi,
    I'm sorry for disturbing you, but I have not even solved this problem.
I do not know which of step take something wrong. I have definitely brought
up the u-dma-buf, and it was opened successfully. But it returned errno
EINVAL when VIDIOC_QBUF ***@***.*** 526 in the attachment)like you before.
    I have prepared a demo attached. I would appreciate  it if you can help
me.
god, please.🙏🙏🙏

Alexander Drozdov ***@***.***> 于2021年11月16日周二 22:23写道：

**Comment by Homio** [comment]
by the way,
    Your program seems can not run for multiple-plane camera.
I comment your code by this:
[image: image.png]
And run for multiple-plane camera, and also get the EINVAL errno like below.
[image: image.png]


Homio ***@***.***> 于2021年12月15日周三 17:08写道：
